import streamlit as st
st.text('Загрузка las файла/файлов')
st.button('LAS')
st.text('')
st.radio('Выберите колонку с именами скважин', ('WELLNAME', 'FORMATION', 'FACIES'))
st.text ('Диапазон глубины в скважине(ах) для определения похожести')
st.slider('Smart depth')
st.slider('End depth')
st.text('')
st.text('Выберите каротажи для обучения сети')
st.checkbox('GR')
st.checkbox('RHOB')
st.checkbox('DENS')
st.selectbox('Выбор предобученной модели (в зависимости от вида каротажей)',('RNN on 4 logs', 'RNN on 6 logs'))
st.checkbox('Нужно ли исключить экземпляры с пропущенными значениями каротажей?')
st.text('Визуализация скважин с пороговым значением похожести')
